### ISSUE TITLE
questions on vagrant file

### ISSUE THREAD

**Issue by d48** [d48/mytestimony#2]
Hey @gear-xander, thanks again for posting up the Vagrant file! I just have some questions for clarity.

## Ubuntu
This line here just notes that it's required that user is on some `ubuntu` instance? 

https://github.com/d48/mytestimony/blob/master/Vagrantfile#L4

If so, can you provide steps and links for `README.md`?

## Comments
Also for different sections of the file, comments would be great, like here: 
https://github.com/d48/mytestimony/blob/master/Vagrantfile#L18 can comment that's it's downloading dependencies for Node.js and Mongodb etc.

## Mongodb
Also last question was regarding mongdob string or base mongodb needing at least a `mytestimony` db. Were you able to run this vagrant file and load up the app and try to post?

**Comment by gear-xander** [comment]
Hey @d48, So I was planning on putting notes in the Vagrant file so you can follow along with what I'm doing line by line but I just haven't done it yet (>_<).  I will get that done this week. The README.md file steps are actually that simple :) All you gotta do is install Vagrant/Virtualbox, clone the repo, and hit vagrant up. It doesn't matter what the host OS is.

The line: https://github.com/d48/mytestimony/blob/master/Vagrantfile#L4 (config.vm.box = "ubuntu/trusty64") refers to the actual vm box ISO that Virtualbox is spinning up. In this case I am using a vanilla ubuntu 14.04 box. You can change the "ubuntu/trusty64" to something else for a different image or OS. Here are some of the different boxes that are out in the community: https://atlas.hashicorp.com/boxes/search

For Mongodb I am using its default database directory at ./data/db https://github.com/d48/mytestimony/blob/master/Vagrantfile#L29
I was able to run the app and save posts without error.

**Comment by d48** [comment]
sweet! thanks for all the info. Will close this
