### ISSUE TITLE
Trying to run app in Vagrant is not working

### ISSUE THREAD

**Issue by d48** [d48/mytestimony#3]
When I try to run `vagrant up`, I get the following error.

![screenshot](http://content.screencast.com/users/User48/folders/Jing/media/9904385e-c63e-43a7-98ca-4bfbf7c5c92a/00000238.png)

I'm using Vagrant versions `1.7.4` and VirtualBox versions `4.1.23`. @gear-xander, can you check into it?

**Comment by d48** [comment]
I upgraded to VirtualBox version `5.0` and it worked. I then tried to view the app via VirtualBox but I got ubuntu login screen and don't have login/password to get access

**Comment by gear-xander** [comment]
Dont use the virtual box GUI to view the app. Just go to localhost:4000

**Comment by gear-xander** [comment]
If you want to log into the VM go to the directory that has the Vagrantfile and type "vagrant ssh" that will log you into the VM. But if you really want to log in using the virtualbox console I believe the default username and password is: vagrant, vagrant.

**Comment by d48** [comment]
Awesome, I was able to get this working by accessing the url via the host. perfect

**Comment by jacigre** [comment]
Where does this environment live? I'd like to get a look also.


*JACIN GREENHILL, Creative Director*

*CA: 949.278.6963 | **NYC: 646.504.8569 *

*Linkedin: www.linkedin.com/in/jacingreenhill/
<http://www.linkedin.com/in/jacingreenhill/>*

*Email: jacin.greenhill@gmail.com <jacin.greenhill@gmail.com>*

**Comment by gear-xander** [comment]
The environment is hosted by Virtual Box (by default) however Vagrant has its own resources to manage the session (for example using the command "vagrant ssh" to log into the box). Once you spin up the Vagrant session with "vagrant up" Virtual Box creates a virtual machine with the image specified in the Vagrantfile. Let me know if this helped or if you have any other questions. 

Vagrant documentation: https://docs.vagrantup.com/v2/getting-started/up.html
